// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2mdvqFDh5Ra__f-XZh5-Of5lZB9yN8YE',
    appId: '1:808367183761:web:4835776adc45a8fcb82c30',
    messagingSenderId: '808367183761',
    projectId: 'shamo-firebase',
    authDomain: 'shamo-firebase.firebaseapp.com',
    storageBucket: 'shamo-firebase.appspot.com',
    measurementId: 'G-PSW8JG52N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkpEKm5rTLw8i3Sxu4IV2k_KLupuYr2XY',
    appId: '1:808367183761:android:7f6592d23ac24c55b82c30',
    messagingSenderId: '808367183761',
    projectId: 'shamo-firebase',
    storageBucket: 'shamo-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rEUB1u8eKSLadslVJvJGUxOMW695kc0',
    appId: '1:808367183761:ios:9ee59f373772f8f2b82c30',
    messagingSenderId: '808367183761',
    projectId: 'shamo-firebase',
    storageBucket: 'shamo-firebase.appspot.com',
    iosClientId: '808367183761-6dgh041fft26h8dihtl7vcf5o0ug2k8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8rEUB1u8eKSLadslVJvJGUxOMW695kc0',
    appId: '1:808367183761:ios:9ee59f373772f8f2b82c30',
    messagingSenderId: '808367183761',
    projectId: 'shamo-firebase',
    storageBucket: 'shamo-firebase.appspot.com',
    iosClientId: '808367183761-6dgh041fft26h8dihtl7vcf5o0ug2k8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamo',
  );
}
